In [1]:
!pip install pandas

Requirement already satisfied: pandas in /home/soul/Documents/my-venv/lib/python3.12/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import numpy as np
import pandas as pd

In [5]:
labels = ['a', 'b', 'c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [7]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data = my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(data=[sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [13]:
ser1 = pd.Series(data=[1,2,3,4],index=['USA', 'GERMANY','USSR', 'JAPAN'])

In [14]:
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [15]:
ser2 = pd.Series([1,2,5,4],['USA','GERMANY', 'ITALY','JAPAN'])

In [17]:
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [18]:
ser1['USA']

1

In [19]:
ser1['JAPAN']

4

In [20]:
ser2['ITALY']

5

In [21]:
ser1+ser2

GERMANY    4.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

## Pandas DataFrame Part-1

In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn

In [3]:
np.random.seed(101)

In [4]:
df = pd.DataFrame(data =randn(5,4), index=['A', 'B','C','D','E'], columns=['W','X','Y','Z'])

In [5]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [6]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [7]:
df['X']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [8]:
df.X   # not a good practice!

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [9]:
df[['W', 'Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [10]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [11]:
df['new']

KeyError: 'new'

In [12]:
df['new'] = df['W'] + df['Y']

In [13]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [14]:
df.drop('new', axis=1)  # Axis 0 means row and 1 means column

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [16]:
df.drop('new', axis=1, inplace=True) # Parmenently delete

In [17]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [18]:
df.drop('A', axis=0)  # Axis 0 means row and 1 means column

          W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [19]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [20]:
df.shape #axis 0=Row-5 rows and axis 1= columns 4

(5, 4)

In [21]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [22]:
df.loc['A'] # loc means location

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [23]:
df.loc['C']

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [24]:
df.iloc[3] # iloc means index location

W    0.188695
X   -0.758872
Y   -0.933237
Z    0.955057
Name: D, dtype: float64

In [25]:
df.loc['B']

W    0.651118
X   -0.319318
Y   -0.848077
Z    0.605965
Name: B, dtype: float64

In [26]:
df.loc['B','Y'] #  single data grap by row and column

-0.8480769834036315

In [27]:
df.loc[['A','B']]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [28]:
df.loc[['A','B'], ['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

## Pandas's DataFrames - Part-2

In [29]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [13]:
df.drop('new', axis=1, inplace=True)

In [30]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [32]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [33]:
df['W'] < 0

A    False
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [34]:
df[df['W'] < 0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [35]:
df['Z'] < 0

A    False
B    False
C     True
D    False
E    False
Name: Z, dtype: bool

In [36]:
df[df['Z'] < 0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [37]:
out = df[df['W']>0]

In [39]:
out

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
out['W']

A    2.706850
B    0.651118
D    0.188695
E    0.190794
Name: W, dtype: float64

In [41]:
out[['X','Z']]

          X         Z
A  0.628133  0.503826
B -0.319318  0.605965
D -0.758872  0.955057
E  1.978757  0.683509

In [42]:
out.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [43]:
out.loc[['A','D']]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
D  0.188695 -0.758872 -0.933237  0.955057

In [44]:
out.loc['C']

KeyError: 'C'

In [45]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df['W'] > 2

A     True
B    False
C    False
D    False
E    False
Name: W, dtype: bool

In [47]:
df[df['W'] > 2]

         W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [48]:
df['Z'] > 0.5

A     True
B     True
C    False
D     True
E     True
Name: Z, dtype: bool

In [35]:
df['W'] > 2 and df['Z'] > 0.5

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [49]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [50]:
(df['W'] > 2) & (df['Z'] > 0.5)

A     True
B    False
C    False
D    False
E    False
dtype: bool

In [51]:
df[(df['W'] > 2) & (df['Z'] > 0.5)]

         W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [52]:
df[(df['W'] > 2) | (df['Z'] > 0.5)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [53]:
df.reset_index() #For peraanent, use inplace = True

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [54]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [55]:
newind = 'CA NY WY OR CO'.split()

In [56]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [57]:
df['states'] = newind

In [58]:
df

          W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [59]:
df.set_index('states') #For permanent, use inplace = True

               W         X         Y         Z
states
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [60]:
df.set_index('states', inplace=True)

In [61]:
df

               W         X         Y         Z
states
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [62]:
df.reset_index(inplace=True)

In [63]:
df

  states         W         X         Y         Z
0     CA  2.706850  0.628133  0.907969  0.503826
1     NY  0.651118 -0.319318 -0.848077  0.605965
2     WY -2.018168  0.740122  0.528813 -0.589001
3     OR  0.188695 -0.758872 -0.933237  0.955057
4     CO  0.190794  1.978757  2.605967  0.683509

## Pandas's DataFrame Part-3

In [64]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [65]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [66]:
list(zip(outside, inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [67]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [68]:
df = pd.DataFrame(data = randn(6,2), index = hier_index, columns=['A', 'B'])

In [69]:
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [70]:
df.loc['G1']

          A         B
1 -0.925874  1.862864
2 -1.133817  0.610478
3  0.386030  2.084019

In [71]:
df.loc['G2']

          A         B
1 -0.376519  0.230336
2  0.681209  1.035125
3 -0.031160  1.939932

In [76]:
df.loc['G1'].loc[2] # Grap the row

A   -1.133817
B    0.610478
Name: 2, dtype: float64

In [71]:
df.loc['G1']['B']  # Grap the column'

1    1.693723
2   -1.159119
3    0.390528
Name: B, dtype: float64

In [72]:
df.loc['G1'].loc[2]['B']

-1.1591194155484297

In [80]:
# xs

In [73]:
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [82]:
df.xs('G1')

          A         B
1 -0.925874  1.862864
2 -1.133817  0.610478
3  0.386030  2.084019

In [83]:
df.index.names

FrozenList([None, None])

In [84]:
df.index.names = ['Group', 'Num']

In [85]:
df

                  A         B
Group Num
G1    1   -0.925874  1.862864
      2   -1.133817  0.610478
      3    0.386030  2.084019
G2    1   -0.376519  0.230336
      2    0.681209  1.035125
      3   -0.031160  1.939932

In [87]:
df

                  A         B
Group Num
G1    1   -0.925874  1.862864
      2   -1.133817  0.610478
      3    0.386030  2.084019
G2    1   -0.376519  0.230336
      2    0.681209  1.035125
      3   -0.031160  1.939932

In [90]:
df.xs('G1')

            A         B
Num
1   -0.925874  1.862864
2   -1.133817  0.610478
3    0.386030  2.084019

In [91]:
df

                  A         B
Group Num
G1    1   -0.925874  1.862864
      2   -1.133817  0.610478
      3    0.386030  2.084019
G2    1   -0.376519  0.230336
      2    0.681209  1.035125
      3   -0.031160  1.939932

In [99]:
df.xs('G1', level='Group')

            A         B
Num
1   -0.925874  1.862864
2   -1.133817  0.610478
3    0.386030  2.084019

In [100]:
df.xs(1, level='Num')

              A         B
Group
G1    -0.925874  1.862864
G2    -0.376519  0.230336

## Missing Data

In [74]:
d = {'A':[1,2,np.nan], 'B':[5, np.nan, np.nan], 'C':[1,2,3]}

In [75]:
df = pd.DataFrame(d)

In [76]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [77]:
df + df

     A     B  C
0  2.0  10.0  2
1  4.0   NaN  4
2  NaN   NaN  6

In [78]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [79]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [80]:
df.dropna(axis=0)

     A    B  C
0  1.0  5.0  1

In [81]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [82]:
df.dropna(axis=0, thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [83]:
df.dropna(axis=0, thresh=3)

     A    B  C
0  1.0  5.0  1

In [84]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [85]:
df.fillna(value='Fill Value')

            A           B  C
0         1.0         5.0  1
1         2.0  Fill Value  2
2  Fill Value  Fill Value  3

In [86]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [87]:
df['A'].mean(numeric_only=True)

1.5

In [88]:
df['A'].fillna(value=df['A'].mean(numeric_only=True))

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## GroupBy

In [90]:
data = {'Company':['GOOG','GOOG','MSFT', 'MSFT', 'FB', 'FB'],
       'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Sales': [200, 120, 340, 124,243, 350]
       }

In [91]:
df = pd.DataFrame(data)

In [92]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [94]:
byComp = df.groupby('Company')

In [95]:
byComp

In [96]:
byComp.mean(numeric_only=True)

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [97]:
byComp.sum(numeric_only=True)

         Sales
Company
FB         593
GOOG       320
MSFT       464

In [98]:
byComp.sum(numeric_only=True).loc['FB']

Sales    593
Name: FB, dtype: int64

In [99]:
df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [100]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [101]:
df.groupby('Company').max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [102]:
df.groupby('Company').min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [103]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [104]:
df.groupby('Company').describe().loc['MSFT']

Sales  count      2.000000
       mean     232.000000
       std      152.735065
       min      124.000000
       25%      178.000000
       50%      232.000000
       75%      286.000000
       max      340.000000
Name: MSFT, dtype: float64

In [105]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

## Merging , Joining and Concatenating

In [117]:
import pandas as pd
import numpy as np

In [106]:
df1 = pd.DataFrame({
    'A':['A0', 'A1', 'A2', 'A3'],
    'B':['B0', 'B1', 'B2', 'B3'],
    'C':['C0', 'C1', 'C2', 'C3'],
    'D':['D0', 'D1', 'D2', 'D3']},
    index=[0,1,2,3])

In [107]:
df2 = pd.DataFrame({
    'A':['A4', 'A5', 'A6', 'A7'],
    'B':['B4', 'B5', 'B6', 'B7'],
    'C':['C4', 'C5', 'C6', 'C7'],
    'D':['D4', 'D5', 'D6', 'D7']},
    index=[4,5,6,7])

In [108]:
df3 = pd.DataFrame({
    'A':['A8', 'A9', 'A10', 'A11'],
    'B':['B8', 'B9', 'B10', 'B11'],
    'C':['C8', 'C9', 'C10', 'C11'],
    'D':['D8', 'D9', 'D10', 'D11']},
    index=[8,9,10,11])

In [109]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [110]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [111]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [113]:
pd.concat([df1, df2, df3]) # Rowwise

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [114]:
pd.concat([df1, df2, df3], axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [118]:
left = pd.DataFrame({
    'key':['K0','K1','K2','K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

In [119]:
right = pd.DataFrame({
    'key':['K0','K1','K2','K3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})

In [120]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [121]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [122]:
pd.merge(left, right, how='inner', on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [123]:
left = pd.DataFrame({
    'key1': ['K0', 'K0', 'K1', 'K2'],
    'key2':['K0', 'K1', 'K0', 'K1'],
    'A':['A0', 'A1', 'A2', 'A3'],
    'B':['B0', 'B1', 'B2', 'B3']
})

In [124]:
right = pd.DataFrame({
    'key1': ['K0', 'K1', 'K1', 'K2'],
    'key2':['K0', 'K0', 'K0', 'K0'],
    'C':['C0', 'C1', 'C2', 'C3'],
    'D':['D0', 'D1', 'D2', 'D3']
})

In [125]:
left

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [126]:
right

  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [127]:
pd.merge(left, right, on=['key1', 'key2'])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [128]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

  key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [129]:
pd.merge(left, right, on=['key1', 'key2'], how='left')

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [130]:
pd.merge(left, right, on=['key1', 'key2'], how='right')

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

### Joining

In [139]:
left = pd.DataFrame({
    'A': ['A0', 'A1','A2'],
    'B': ['B0', 'B1', 'B2'],},
    index = ['K0', 'K1', 'K2'])

In [140]:
right = pd.DataFrame({
    'C': ['C0', 'C1','C2'],
    'D': ['D0', 'D1', 'D2'],},
    index = ['K0', 'K2', 'K3'])

In [137]:
left

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [138]:
right

     C   D
K0  C0  D0
K2  C1  D1
K3  C2  D2

In [141]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C1   D1

In [135]:
left.join(right, how='outer')

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2

## Operations

In [142]:
df = pd.DataFrame({
    'col1':[1,2,3,4],
    'col2':[444,555,666,444],
    'col3':['abc', 'def', 'ghi', 'xyz']
})

In [143]:
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [144]:
df['col2']

0    444
1    555
2    666
3    444
Name: col2, dtype: int64

In [145]:
df['col2'].unique()

array([444, 555, 666])

In [146]:
len(df['col2'].unique())

3

In [151]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [152]:
df['col2'].nunique()

3

In [148]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [153]:
df['col1']>2

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [155]:
df['col2'] == 444

0     True
1    False
2    False
3     True
Name: col2, dtype: bool

In [156]:
df[(df['col1']>2) & (df['col2'] == 444)]

   col1  col2 col3
3     4   444  xyz

In [164]:
def times2(x):
    return x*2

In [165]:
#lambda x:x*2

In [158]:
df['col1']

0    1
1    2
2    3
3    4
Name: col1, dtype: int64

In [159]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [160]:
df['col2'].apply(times2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [162]:
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [161]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [163]:
df['col3'].apply(times2)

0    abcabc
1    defdef
2    ghighi
3    xyzxyz
Name: col3, dtype: object

In [166]:
df['col2'].apply(lambda x: x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [167]:
df.sort_values(by= 'col2')

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [168]:
df.isnull()

    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [169]:
data = {
    'A':['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'B': ['one', 'one', 'two', 'two', 'one', 'one'],
    'C': ['x', 'y', 'x', 'y', 'x', 'y'],
    'D': [1,3,2,5,4,1]
}

In [170]:
df = pd.DataFrame(data)

In [171]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [172]:
df.pivot_table(values='D', index=['A','B'], columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

## Data Input and Output

In [174]:
!pip install sqlalchemy
!pip install lxml
!pip install html5lib
!pip install BeautifulSoup4
!pip install xlrd
!pip install openpyxl

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.45-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from sqlalchemy) (4.12.2)
Downloading sqlalchemy-2.0.45-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 12.0 MB/s eta 0:00:00m eta 0:00:010:01:01
Downloading greenlet-3.3.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (609 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 609.9/609.9 kB 11.7 MB/s eta 0:00:0031m13.4 MB/s eta 0:00:01
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.3.0 sqlalchemy-2.0.45
Requirement already satisfied: lxml in /home/soul/Documents/my-venv/lib/python3.12/site-packages (5.2.2)
Requirement already satisfied: html5lib in /home/soul/Documents/my-venv/lib/python3.12/site-packages (1.1)
Requirement already satisfied: six>=1.9 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: BeautifulSoup4 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from BeautifulSoup4) (2.5)
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 3.5 MB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Requirement already satisfied: openpyxl in /home/soul/Documents/my-venv/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from openpyxl) (2.0.0)

In [175]:
pd.read_csv('example')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [176]:
df = pd.read_csv('example')

In [177]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [178]:
df.to_csv('my_output')

In [179]:
pd.read_csv('my_output')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [180]:
df.to_csv('my_output', index=False)

In [181]:
pd.read_csv('my_output')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [182]:
pd.read_excel('Excel_Sample.xlsx', sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [183]:
df = pd.read_excel('Excel_Sample.xlsx', sheet_name='Sheet1')

In [184]:
df.to_excel('my_excel.xlsx', sheet_name='new_sheet')

In [185]:
pd.read_excel('my_excel.xlsx', sheet_name='new_sheet')

   Unnamed: 0.1  Unnamed: 0   a   b   c   d
0             0           0   0   1   2   3
1             1           1   4   5   6   7
2             2           2   8   9  10  11
3             3           3  12  13  14  15

In [186]:
data = pd.read_html('https://www.fdic.gov/bank-failures/failed-bank-list')

In [187]:
type(data)

list

In [188]:
data

[                                            Bank Name                City  \
 0                        The Santa Anna National Bank          Santa Anna
 1                                Pulaski Savings Bank             Chicago
 2                  The First National Bank of Lindsay             Lindsay
 3               Republic First Bank dba Republic Bank        Philadelphia
 4                                       Citizens Bank            Sac City
 5                            Heartland Tri-State Bank             Elkhart
 6                                 First Republic Bank       San Francisco
 7                                      Signature Bank            New York
 8                                 Silicon Valley Bank         Santa Clara
 9                                   Almena State Bank              Almena
 10                         First City Bank of Florida   Fort Walton Beach
 11                               The First State Bank       Barboursville
 12                                 Ericson State Bank             Ericson
 13                   City National Bank of New Jersey              Newark
 14                                      Resolute Bank              Maumee
 15                              Louisa Community Bank              Louisa
 16                               The Enloe State Bank              Cooper
 17                Washington Federal Bank for Savings             Chicago
 18    The Farmers and Merchants State Bank of Argonia             Argonia
 19                                Fayette County Bank          Saint Elmo
 20  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 21                                     First NBC Bank         New Orleans
 22                                      Proficio Bank  Cottonwood Heights
 23                      Seaway Bank and Trust Company             Chicago
 24                             Harvest Community Bank          Pennsville

             State   Cert                Acquiring Institution  \
 0           Texas   5520            Coleman County State Bank
 1        Illinois  28611                      Millennium Bank
 2        Oklahoma   4134               First Bank & Trust Co.
 3    Pennsylvania  27332    Fulton Bank, National Association
 4            Iowa   8758            Iowa Trust & Savings Bank
 5          Kansas  25851               Dream First Bank, N.A.
 6      California  59017            JPMorgan Chase Bank, N.A.
 7        New York  57053                  Flagstar Bank, N.A.
 8      California  24735  First Citizens Bank & Trust Company
 9          Kansas  15426                          Equity Bank
 10        Florida  16748            United Fidelity Bank, fsb
 11  West Virginia  14361                       MVB Bank, Inc.
 12       Nebraska  18265           Farmers and Merchants Bank
 13     New Jersey  21111                      Industrial Bank
 14           Ohio  58317                   Buckeye State Bank
 15       Kentucky  58112    Kentucky Farmers Bank Corporation
 16          Texas  10716                   Legend Bank, N. A.
 17       Illinois  30570                   Royal Savings Bank
 18         Kansas  17719                          Conway Bank
 19       Illinois   1802            United Fidelity Bank, fsb
 20      Wisconsin  30003  First-Citizens Bank & Trust Company
 21      Louisiana  58302                         Whitney Bank
 22           Utah  35495                    Cache Valley Bank
 23       Illinois  19328                  State Bank of Texas
 24     New Jersey  34951  First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       June 27, 2025                 10549
 1    January 17, 2025                 10548
 2    October 18, 2024                 10547
 3      April 26, 2024                 10546
 4    November 3, 2023                 10545
 5       July 28, 2023                 10544
 6         May 1, 2023                 10543
 7      March 12, 2023                 10540
 8      March 10, 2023                 10539
 9    October 23, 2020                 10538
 10   October 16, 2020                 10537
 11      April 3, 2020                 10536
 12  February 14, 2020                 10535
 13   November 1, 2019                 10534
 14   October 25, 2019                 10533
 15   October 25, 2019                 10532
 16       May 31, 2019                 10531
 17  December 15, 2017                 10530
 18   October 13, 2017                 10529
 19       May 26, 2017                 10528
 20        May 5, 2017                 10527
 21     April 28, 2017                 10526
 22      March 3, 2017                 10525
 23   January 27, 2017                 10524
 24   January 13, 2017                 10523  ]

In [190]:
data[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

In [191]:
data[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545

In [193]:
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [197]:
from sqlalchemy import create_engine

In [198]:
engine = create_engine('sqlite:///:memory:')

In [199]:
df.to_sql('my_sql_table', con=engine) # save data into a sql table

4

In [200]:
sqldf = pd.read_sql('my_sql_table', con=engine)

In [201]:
sqldf

   index  Unnamed: 0   a   b   c   d
0      0           0   0   1   2   3
1      1           1   4   5   6   7
2      2           2   8   9  10  11
3      3           3  12  13  14  15