In [1]:
!pip install pandas

Requirement already satisfied: pandas in /home/soul/Documents/my-venv/lib/python3.12/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import numpy as np
import pandas as pd

In [5]:
labels = ['a', 'b', 'c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [7]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data = my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(data=[sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [13]:
ser1 = pd.Series(data=[1,2,3,4],index=['USA', 'GERMANY','USSR', 'JAPAN'])

In [14]:
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [15]:
ser2 = pd.Series([1,2,5,4],['USA','GERMANY', 'ITALY','JAPAN'])

In [17]:
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [18]:
ser1['USA']

1

In [19]:
ser1['JAPAN']

4

In [20]:
ser2['ITALY']

5

In [21]:
ser1+ser2

GERMANY    4.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

## Pandas DataFrame Part-1

In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn

In [3]:
np.random.seed(101)

In [4]:
df = pd.DataFrame(data =randn(5,4), index=['A', 'B','C','D','E'], columns=['W','X','Y','Z'])

In [5]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [5]:
df['W']

A   -0.711281
B   -0.762516
C   -0.705479
D   -0.534714
E    1.098538
Name: W, dtype: float64

In [6]:
df['X']

A    0.004785
B    0.743237
C   -0.103857
D   -0.817018
E   -0.118228
Name: X, dtype: float64

In [36]:
df.X   # not a good practice!

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [7]:
df[['W', 'Y']]

          W         Y
A -0.711281 -0.301801
B -0.762516 -2.077949
C -0.705479  0.209148
D -0.534714 -0.172537
E  1.098538  0.972034

In [8]:
df[['W','Z']]

          W         Z
A -0.711281  0.672053
B -0.762516  1.203745
C -0.705479  0.488712
D -0.534714  0.270206
E  1.098538  0.344192

In [39]:
df['new']

KeyError: 'new'

In [10]:
df['new'] = df['W'] + df['Y']

In [11]:
df

          W         X         Y         Z       new
A -0.711281  0.004785 -0.301801  0.672053 -1.013082
B -0.762516  0.743237 -2.077949  1.203745 -2.840464
C -0.705479 -0.103857  0.209148  0.488712 -0.496332
D -0.534714 -0.817018 -0.172537  0.270206 -0.707251
E  1.098538 -0.118228  0.972034  0.344192  2.070572

In [41]:
df.drop('new', axis=1)  # Axis 0 means row and 1 means column

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [43]:
df.drop('new', axis=1, inplace=True) # Parmenently delete

In [44]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [45]:
df.drop('A', axis=0)  # Axis 0 means row and 1 means column

          W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [47]:
df.shape #axis 0=Row-5 rows and axis 1= columns 4

(5, 4)

In [49]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [50]:
df.loc['A'] # loc means location

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [51]:
df.loc['C']

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [52]:
df.iloc[3] # iloc means index location

W    0.188695
X   -0.758872
Y   -0.933237
Z    0.955057
Name: D, dtype: float64

In [53]:
df.loc['B']

W    0.651118
X   -0.319318
Y   -0.848077
Z    0.605965
Name: B, dtype: float64

In [54]:
df.loc['B','Y'] #  single data grap by row and column

-0.8480769834036315

In [55]:
df.loc[['A','B']]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [56]:
df.loc[['A','B'], ['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

## Pandas's DataFrames - Part-2

In [12]:
df

          W         X         Y         Z       new
A -0.711281  0.004785 -0.301801  0.672053 -1.013082
B -0.762516  0.743237 -2.077949  1.203745 -2.840464
C -0.705479 -0.103857  0.209148  0.488712 -0.496332
D -0.534714 -0.817018 -0.172537  0.270206 -0.707251
E  1.098538 -0.118228  0.972034  0.344192  2.070572

In [13]:
df.drop('new', axis=1, inplace=True)

In [6]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [7]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [8]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [9]:
df['W'] < 0

A    False
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [10]:
df[df['W'] < 0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [13]:
df['Z'] < 0

A    False
B    False
C     True
D    False
E    False
Name: Z, dtype: bool

In [15]:
df[df['Z'] < 0]

          W         X         Y         Z
C -2.018168  0.740122  0.528813 -0.589001

In [18]:
out = df[df['W']>0]

In [19]:
out

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [20]:
out['W']

A    2.706850
B    0.651118
D    0.188695
E    0.190794
Name: W, dtype: float64

In [21]:
out[['X','Z']]

          X         Z
A  0.628133  0.503826
B -0.319318  0.605965
D -0.758872  0.955057
E  1.978757  0.683509

In [22]:
out.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [23]:
out.loc[['A','D']]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
D  0.188695 -0.758872 -0.933237  0.955057

In [24]:
out.loc['C']

KeyError: 'C'

In [26]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
df['W'] > 2

A     True
B    False
C    False
D    False
E    False
Name: W, dtype: bool

In [28]:
df[df['W'] > 2]

         W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [29]:
df['Z'] > 0.5

A     True
B     True
C    False
D     True
E     True
Name: Z, dtype: bool

In [35]:
df['W'] > 2 and df['Z'] > 0.5

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [36]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [34]:
(df['W'] > 2) & (df['Z'] > 0.5)

A     True
B    False
C    False
D    False
E    False
dtype: bool

In [37]:
df[(df['W'] > 2) & (df['Z'] > 0.5)]

         W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

In [38]:
df[(df['W'] > 2) | (df['Z'] > 0.5)]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [40]:
df.reset_index() #For peraanent, use inplace = True

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [41]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
newind = 'CA NY WY OR CO'.split()

In [43]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [44]:
df['states'] = newind

In [45]:
df

          W         X         Y         Z states
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [50]:
df.set_index('states') #Forpermanent, use inplace = True

               W         X         Y         Z
states
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [51]:
df.set_index('states', inplace=True)

In [52]:
df

               W         X         Y         Z
states
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [54]:
df.reset_index(inplace=True)

In [55]:
df

  states         W         X         Y         Z
0     CA  2.706850  0.628133  0.907969  0.503826
1     NY  0.651118 -0.319318 -0.848077  0.605965
2     WY -2.018168  0.740122  0.528813 -0.589001
3     OR  0.188695 -0.758872 -0.933237  0.955057
4     CO  0.190794  1.978757  2.605967  0.683509

## Pandas's DataFrame Part-3

In [56]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [63]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [64]:
list(zip(outside, inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [59]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [69]:
df = pd.DataFrame(data = randn(6,2), index = hier_index, columns=['A', 'B'])

In [67]:
df

             A         B
G1 1  1.025984 -0.156598
   2 -0.031579  0.649826
   3  2.154846 -0.610259
G2 1 -0.755325 -0.346419
   2  0.147027 -0.479448
   3  0.558769  1.024810

In [70]:
df.loc['G1']

          A         B
1 -0.925874  1.862864
2 -1.133817  0.610478
3  0.386030  2.084019

In [71]:
df.loc['G2']

          A         B
1 -0.376519  0.230336
2  0.681209  1.035125
3 -0.031160  1.939932

In [76]:
df.loc['G1'].loc[2] # Grap the row

A   -1.133817
B    0.610478
Name: 2, dtype: float64

In [77]:
df.loc['G1']['B']  # Grap the column'

1    1.862864
2    0.610478
3    2.084019
Name: B, dtype: float64

In [79]:
df.loc['G1'].loc[2]['B']

0.6104779075384634

In [80]:
# xs

In [81]:
df

             A         B
G1 1 -0.925874  1.862864
   2 -1.133817  0.610478
   3  0.386030  2.084019
G2 1 -0.376519  0.230336
   2  0.681209  1.035125
   3 -0.031160  1.939932

In [82]:
df.xs('G1')

          A         B
1 -0.925874  1.862864
2 -1.133817  0.610478
3  0.386030  2.084019

In [83]:
df.index.names

FrozenList([None, None])

In [84]:
df.index.names = ['Group', 'Num']

In [85]:
df

                  A         B
Group Num
G1    1   -0.925874  1.862864
      2   -1.133817  0.610478
      3    0.386030  2.084019
G2    1   -0.376519  0.230336
      2    0.681209  1.035125
      3   -0.031160  1.939932

In [87]:
df

                  A         B
Group Num
G1    1   -0.925874  1.862864
      2   -1.133817  0.610478
      3    0.386030  2.084019
G2    1   -0.376519  0.230336
      2    0.681209  1.035125
      3   -0.031160  1.939932

In [90]:
df.xs('G1')

            A         B
Num
1   -0.925874  1.862864
2   -1.133817  0.610478
3    0.386030  2.084019

In [91]:
df

                  A         B
Group Num
G1    1   -0.925874  1.862864
      2   -1.133817  0.610478
      3    0.386030  2.084019
G2    1   -0.376519  0.230336
      2    0.681209  1.035125
      3   -0.031160  1.939932

In [99]:
df.xs('G1', level='Group')

            A         B
Num
1   -0.925874  1.862864
2   -1.133817  0.610478
3    0.386030  2.084019

In [100]:
df.xs(1, level='Num')

              A         B
Group
G1    -0.925874  1.862864
G2    -0.376519  0.230336

## Missing Data

In [101]:
d = {'A':[1,2,np.nan], 'B':[5, np.nan, np.nan], 'C':[1,2,3]}

In [102]:
df = pd.DataFrame(d)

In [103]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [104]:
df + df

     A     B  C
0  2.0  10.0  2
1  4.0   NaN  4
2  NaN   NaN  6

In [105]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [106]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [108]:
df.dropna(axis=0)

     A    B  C
0  1.0  5.0  1

In [109]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [110]:
df.dropna(axis=0, thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [111]:
df.dropna(axis=0, thresh=3)

     A    B  C
0  1.0  5.0  1

In [112]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [113]:
df.fillna(value='Fill Value')

            A           B  C
0         1.0         5.0  1
1         2.0  Fill Value  2
2  Fill Value  Fill Value  3

In [116]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [121]:
df['A'].mean(numeric_only=True)

1.5

In [122]:
df['A'].fillna(value=df['A'].mean(numeric_only=True))

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [123]:
## GroupBy

In [124]:
data = {'Company':['GOOG','GOOG','MSFT', 'MSFT', 'FB', 'FB'],
       'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Sales': [200, 120, 340, 124,243, 350]
       }

In [125]:
df = pd.DataFrame(data)

In [126]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [128]:
byComp = df.groupby('Company')

In [130]:
byComp.mean(numeric_only=True)

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [131]:
byComp.sum(numeric_only=True)

         Sales
Company
FB         593
GOOG       320
MSFT       464

In [132]:
byComp.sum(numeric_only=True).loc['FB']

Sales    593
Name: FB, dtype: int64

In [133]:
df.groupby('Company').count()

         Person  Sales
Company
FB            2      2
GOOG          2      2
MSFT          2      2

In [134]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [135]:
df.groupby('Company').max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [136]:
df.groupby('Company').min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [139]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [140]:
df.groupby('Company').describe().loc['MSFT']

Sales  count      2.000000
       mean     232.000000
       std      152.735065
       min      124.000000
       25%      178.000000
       50%      232.000000
       75%      286.000000
       max      340.000000
Name: MSFT, dtype: float64

In [141]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000