In [1]:
!pip install pandas

Requirement already satisfied: pandas in /home/soul/Documents/my-venv/lib/python3.12/site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /home/soul/Documents/my-venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import numpy as np
import pandas as pd

In [5]:
labels = ['a', 'b', 'c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [7]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data = my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(data=[sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [13]:
ser1 = pd.Series(data=[1,2,3,4],index=['USA', 'GERMANY','USSR', 'JAPAN'])

In [14]:
ser1

USA        1
GERMANY    2
USSR       3
JAPAN      4
dtype: int64

In [15]:
ser2 = pd.Series([1,2,5,4],['USA','GERMANY', 'ITALY','JAPAN'])

In [17]:
ser2

USA        1
GERMANY    2
ITALY      5
JAPAN      4
dtype: int64

In [18]:
ser1['USA']

1

In [19]:
ser1['JAPAN']

4

In [20]:
ser2['ITALY']

5

In [21]:
ser1+ser2

GERMANY    4.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

## Pandas DataFrame Part-1

In [22]:
import numpy as np
import pandas as pd

In [24]:
from numpy.random import randn

In [25]:
np.random.seed(101)

In [26]:
df = pd.DataFrame(data =randn(5,4), index=['A', 'B','C','D','E'], columns=['W','X','Y','Z'])

In [27]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [29]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [30]:
df['X']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [32]:
df.X   # not a good practice!

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [34]:
df[['W', 'Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [35]:
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [37]:
df['new']

KeyError: 'new'

In [38]:
df['new'] = df['W'] + df['Y']

In [39]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [41]:
df.drop('new', axis=1)  # Axis 0 means row and 1 means column

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [43]:
df.drop('new', axis=1, inplace=True) # Parmenently delete

In [44]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [45]:
df.drop('A', axis=0)  # Axis 0 means row and 1 means column

          W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [46]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [52]:
df.shape #axis 0=Row-5 rows and axis 1= columns 4

(5, 4)

In [53]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [49]:
df.loc['A'] # loc means location

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [50]:
df.loc['C']

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [51]:
df.iloc[3] # iloc means index location

W    0.188695
X   -0.758872
Y   -0.933237
Z    0.955057
Name: D, dtype: float64

In [54]:
df.loc['B']

W    0.651118
X   -0.319318
Y   -0.848077
Z    0.605965
Name: B, dtype: float64

In [56]:
df.loc['B','Y'] #  single data grap by row and column

-0.8480769834036315

In [57]:
df.loc[['A','B']]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [58]:
df.loc[['A','B'], ['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077